function plot_q4_dpsir(figurePath)
% PLOT_Q4_DPSIR  绘制全民体重问题DPSIR危险机会传导框架。

fontName = q4_choose_font();
fig = figure('Visible', 'off', 'Color', 'w', 'Position', [50 80 1800 820]);
colors = [0.20 0.47 0.66; 0.82 0.45 0.22; 0.34 0.60 0.45; 0.69 0.35 0.38; 0.42 0.45 0.58];
titles = {'D 驱动力','P 压力','S 状态','I 影响','R 响应'};
contents = { ...
    '人口年龄结构\newline工作生活方式变化\newline食物与运动环境', ...
    '能量摄入与活动失衡\newline睡眠不足\newline依从与支持不足', ...
    '成人超重肥胖率\newline成人超重肥胖人数\newline结构不确定性', ...
    '慢病风险与医疗压力\newline健康劳动力损失\newline不直接虚构病例或费用', ...
    '扩大覆盖与长期坚持\newline分人群生活方式方案\newline持续监测和滚动校准'};
x = [0.025 0.225 0.425 0.625 0.825];
for i = 1:5
    annotation(fig, 'textbox', [x(i) 0.34 0.15 0.32], ...
        'String', sprintf('%s\n\n%s', titles{i}, contents{i}), ...
        'FontName', fontName, 'FontSize', 13, 'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'Color', 'w', 'BackgroundColor', colors(i,:), 'EdgeColor', colors(i,:)*0.75, ...
        'LineWidth', 1.4, 'FitBoxToText', 'off');
end
for i = 1:4
    annotation(fig, 'arrow', [x(i)+0.155 x(i+1)-0.008], [0.50 0.50], ...
        'LineWidth', 2.2, 'Color', [0.25 0.25 0.25], 'HeadWidth', 10, 'HeadLength', 10);
end
annotation(fig, 'arrow', [0.90 0.29], [0.27 0.27], ...
    'LineWidth', 1.8, 'Color', [0.32 0.32 0.32], 'HeadWidth', 9, 'HeadLength', 9);
annotation(fig, 'textbox', [0.42 0.20 0.36 0.07], ...
    'String', '政策响应反馈到压力控制与状态改善', 'FontName', fontName, ...
    'FontSize', 12, 'HorizontalAlignment', 'center', ...
    'EdgeColor', 'none', 'Color', [0.32 0.32 0.32]);
annotation(fig, 'textbox', [0.12 0.78 0.76 0.12], ...
    'String', '全民体重危机中的典型危险与机会：DPSIR传导框架', ...
    'FontName', fontName, 'FontSize', 22, 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', 'EdgeColor', 'none');
annotation(fig, 'textbox', [0.12 0.10 0.76 0.08], ...
    'String', '危险：率与人数负担上升、依从折损、单一方案失配、远期预测不确定  |  机会：覆盖扩张、分层干预、数字监测、滚动评估', ...
    'FontName', fontName, 'FontSize', 13, 'HorizontalAlignment', 'center', ...
    'EdgeColor', 'none', 'Color', [0.25 0.25 0.25]);
exportgraphics(fig, figurePath, 'Resolution', 300);
close(fig);
end

function fontName = q4_choose_font()
preferred = {'Microsoft YaHei', 'SimHei', 'SimSun'};
available = listfonts;
fontName = get(groot, 'defaultAxesFontName');
for i = 1:numel(preferred)
    if any(strcmpi(available, preferred{i}))
        fontName = preferred{i};
        return;
    end
end
end
