function plot_q2_mechanism()
%PLOT_Q2_MECHANISM Draw the multi-layer mechanism of weight-loss failure.

fontName = choose_q2_chinese_font();
fig = figure('Color', 'w', 'Position', [100, 100, 1500, 900], ...
    'Visible', 'on');
axis off;

colors = [
    0.13, 0.52, 0.55;
    0.25, 0.43, 0.72;
    0.88, 0.58, 0.16;
    0.75, 0.28, 0.25
];
titles = {'行为执行层', '心理调节层', '支持环境层', '生理医学层'};
details = {
    '热量控制、体力活动、自我监测';
    '自我效能、动机、情绪性与失控性进食';
    '时间、家庭、物流、专业监督和医患沟通';
    '食欲增强、能量消耗下降、疾病与药物影响'
};
xPositions = [0.04, 0.28, 0.52, 0.76];

for i = 1:4
    annotation(fig, 'textbox', [xPositions(i), 0.66, 0.20, 0.20], ...
        'String', {titles{i}; details{i}}, ...
        'FontName', fontName, 'FontSize', 17, ...
        'FontWeight', 'bold', 'Color', [1, 1, 1], ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'BackgroundColor', colors(i, :), 'EdgeColor', colors(i, :) .* 0.75, ...
        'LineWidth', 1.5);
    annotation(fig, 'arrow', [xPositions(i) + 0.10, 0.50], [0.65, 0.53], ...
        'LineWidth', 1.8, 'Color', colors(i, :));
end

annotation(fig, 'textbox', [0.23, 0.37, 0.54, 0.15], ...
    'String', {'长期能量缺口难以维持'; ...
    '摄入回升 + 消耗不足 + 纠偏不及时'}, ...
    'FontName', fontName, 'FontSize', 20, 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'BackgroundColor', [0.94, 0.95, 0.94], 'EdgeColor', [0.35, 0.40, 0.38], ...
    'LineWidth', 1.5);
annotation(fig, 'arrow', [0.50, 0.50], [0.37, 0.27], ...
    'LineWidth', 2.2, 'Color', [0.28, 0.30, 0.29]);
annotation(fig, 'textbox', [0.34, 0.10, 0.32, 0.15], ...
    'String', {'减重不成功'; '初始减重不足、治疗退出或长期反弹'}, ...
    'FontName', fontName, 'FontSize', 21, 'FontWeight', 'bold', ...
    'Color', [1, 1, 1], 'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', 'BackgroundColor', [0.55, 0.15, 0.18], ...
    'EdgeColor', [0.40, 0.08, 0.10], 'LineWidth', 1.8);
annotation(fig, 'textbox', [0.04, 0.91, 0.92, 0.06], ...
    'String', '减肥失败的行为—心理—环境—生理作用机制', ...
    'FontName', fontName, 'FontSize', 24, 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', 'EdgeColor', 'none');

drawnow;
end
