function checks = self_check_q2(data, results)
%SELF_CHECK_Q2 Validate inputs, calculations and Python reference values.

checks = struct('name', {}, 'passed', {}, 'value', {}, ...
    'expected', {}, 'notes', {});
baseline = results.scenarios(1);

checks(end + 1) = make_check('factor_count', data.count == 15, ...
    sprintf('%d', data.count), '15', '因素总数');
checks(end + 1) = make_check('factor_ids_unique', ...
    numel(unique(data.factor_id)) == 15, ...
    sprintf('%d', numel(unique(data.factor_id))), '15', '编号唯一');
checks(end + 1) = make_check('numeric_inputs_complete', ...
    all(isfinite(data.baseline_matrix(:))), ...
    logical_text(all(isfinite(data.baseline_matrix(:)))), 'true', '无数值缺失');
checks(end + 1) = make_check('direction_consistency', ...
    max(abs(data.consistency - data.support_count ./ data.measurement_count)) < 1e-12, ...
    sprintf('%.3e', max(abs(data.consistency - ...
    data.support_count ./ data.measurement_count))), '<1e-12', '统一方向后的一致率');
checks(end + 1) = make_check('source_traceability', ...
    all(~cellfun(@isempty, data.source_location)) && ...
    all(~cellfun(@isempty, data.original_row_name)), ...
    logical_text(all(~cellfun(@isempty, data.source_location)) && ...
    all(~cellfun(@isempty, data.original_row_name))), 'true', '表号与原文行名');

m4 = find(strcmp(data.factor_id, 'M4'), 1);
m4Passed = ~isempty(m4) && data.n_studies(m4) == 7 && ...
    data.measurement_count(m4) == 8 && data.support_count(m4) == 7;
checks(end + 1) = make_check('M4_counts', m4Passed, ...
    sprintf('%d/%d/%d', data.n_studies(m4), ...
    data.measurement_count(m4), data.support_count(m4)), ...
    '7/8/7', '研究篇数/方向判断次数/支持次数');

checks(end + 1) = make_check('critic_weights_sum', ...
    abs(sum(baseline.weights) - 1) < 1e-12, ...
    sprintf('%.15f', sum(baseline.weights)), '1', '权重和');
checks(end + 1) = make_check('topsis_range', ...
    all(baseline.scores >= 0 & baseline.scores <= 1), ...
    sprintf('%.12f..%.12f', min(baseline.scores), max(baseline.scores)), ...
    '[0,1]', '贴近度范围');
checks(end + 1) = make_check('ranking_complete', ...
    numel(baseline.ranks) == 15, sprintf('%d', numel(baseline.ranks)), ...
    '15', '覆盖全部因素');
checks(end + 1) = make_check('tie_ranking', ...
    isequal(rank_with_ties([0.9; 0.8; 0.8; 0.7])', [1, 2, 2, 4]), ...
    mat2str(rank_with_ties([0.9; 0.8; 0.8; 0.7])'), ...
    '[1 2 2 4]', '并列名次');

expectedWeights = [0.23819447, 0.41956168, 0.34224385];
expectedScores = [
    0.8381794765725818;
    0.4663273555781836;
    0.4663273555781836;
    0.3626553396500982;
    0.3243348792738156;
    0.2920806092706343;
    0.2920806092706343;
    0.1516328729477448;
    0.2650394908247277;
    0.2650394908247277;
    0.2650394908247277;
    0.0977213248399505;
    0.2879903941846780;
    0.1685543543972684;
    0.2751288438750224
];
weightError = max(abs(baseline.weights - expectedWeights));
scoreError = max(abs(baseline.scores - expectedScores));
checks(end + 1) = make_check('python_weight_reference_error', ...
    weightError <= 1e-8, sprintf('%.3e', weightError), '<=1e-8', ...
    'MATLAB与Python基准权重误差');
checks(end + 1) = make_check('python_score_reference_error', ...
    scoreError <= 1e-8, sprintf('%.3e', scoreError), '<=1e-8', ...
    'MATLAB与Python基准TOPSIS误差');

overlaps = [results.scenarios.top5_overlap];
rhos = [results.scenarios.spearman_rho];
checks(end + 1) = make_check('all_top5_overlap', all(overlaps == 5), ...
    mat2str(overlaps), 'all 5', '六场景前五重合');
checks(end + 1) = make_check('all_spearman_rho', all(rhos >= 0.8), ...
    sprintf('min %.12f', min(rhos)), '>=0.8', '六场景排序相关');

if any(~[checks.passed])
    failedNames = {checks(~[checks.passed]).name};
    error('Q2:SelfCheckFailed', 'Q2 checks failed: %s', ...
        strjoin(failedNames, ', '));
end
end


function item = make_check(name, passed, value, expected, notes)
item.name = name;
item.passed = logical(passed);
item.value = value;
item.expected = expected;
item.notes = notes;
end


function text = logical_text(value)
if value
    text = 'true';
else
    text = 'false';
end
end
